output   = "models"
wipe     = true
templates = [
  "/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.14.0/templates/main", # sqlboilerのテンプレートディレクトリ
  "/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.14.0/templates/test", # sqlboilerのテスト用テンプレートディレクトリ
  "templates" # カスタムテンプレートディレクトリ
]

[psql]
  dbname = "db"
  host   = "sqlboiler-postgres"
  port   = 5432
  user   = "usr"
  pass   = "password"
  sslmode = "disable"